/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Site } from "./Site";
export { Site } from "./Site";
export namespace Components {
    interface BinotypeSite {
        /**
          * @default false
         */
        "debug": boolean | "site" | "context";
        "site"?: Site | string;
    }
}
declare global {
    interface HTMLBinotypeSiteElement extends Components.BinotypeSite, HTMLStencilElement {
    }
    var HTMLBinotypeSiteElement: {
        prototype: HTMLBinotypeSiteElement;
        new (): HTMLBinotypeSiteElement;
    };
    interface HTMLElementTagNameMap {
        "binotype-site": HTMLBinotypeSiteElement;
    }
}
declare namespace LocalJSX {
    interface BinotypeSite {
        /**
          * @default false
         */
        "debug"?: boolean | "site" | "context";
        "site"?: Site | string;
    }

    interface BinotypeSiteAttributes {
        "site": Site | string;
        "debug": string;
    }

    interface IntrinsicElements {
        "binotype-site": Omit<BinotypeSite, keyof BinotypeSiteAttributes> & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes]?: BinotypeSite[K] } & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes as `attr:${K}`]?: BinotypeSiteAttributes[K] } & { [K in keyof BinotypeSite & keyof BinotypeSiteAttributes as `prop:${K}`]?: BinotypeSite[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "binotype-site": LocalJSX.IntrinsicElements["binotype-site"] & JSXBase.HTMLAttributes<HTMLBinotypeSiteElement>;
        }
    }
}
