/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Site } from "./Site";
export { Site } from "./Site";
export namespace Components {
    interface BinotypeSite {
        "site"?: Site | string;
    }
}
declare global {
    interface HTMLBinotypeSiteElement extends Components.BinotypeSite, HTMLStencilElement {
    }
    var HTMLBinotypeSiteElement: {
        prototype: HTMLBinotypeSiteElement;
        new (): HTMLBinotypeSiteElement;
    };
    interface HTMLElementTagNameMap {
        "binotype-site": HTMLBinotypeSiteElement;
    }
}
declare namespace LocalJSX {
    interface BinotypeSite {
        "site"?: Site | string;
    }
    interface IntrinsicElements {
        "binotype-site": BinotypeSite;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "binotype-site": LocalJSX.BinotypeSite & JSXBase.HTMLAttributes<HTMLBinotypeSiteElement>;
        }
    }
}
